language: csharp
mono: none
dotnet: 2.1.502
sudo: false

solution: src/csharp/service-mesh.sln

install:
 - dotnet restore src/csharp/service-mesh.sln
# - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner

script:
 - dotnet build src/csharp/service-mesh.sln
 - dotnet test src/csharp/service-mesh.sln

# safelist
branches:
  only:
  - master
  - stable
  - develop
  - experimental

after_success:
  - bash <(curl -s https://codecov.io/bash)
